filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    json.keys_under_root: true         # Parse JSON and place keys at the root
    json.add_error_key: true            # Add an error key if parsing fails
    json.message_key: message            # Specify the message key for logs
    processors:
      - add_docker_metadata: ~
      - drop_event:
          when:
            equals:
              error.message: "Failed to parse docker metadata"
      
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"

setup.kibana:
  host: "http://kibana:5601"


# filebeat.inputs:
# - type: container
#   paths:
#     - /var/lib/docker/containers/*/*.log
#   json.keys_under_root: false  # Disable JSON parsing
#   processors:
#     - dissect:
#         tokenizer: "%{log}"
#         field: "message"
#         target_prefix: ""
#     - drop_fields:
#         fields: ["source", "input", "host", "agent"]  # Drop unnecessary fields
